from ai_redditor_service.extensions import db

class Record(db.Model):
    '''
    A post (title/body pair) generated by the model.

    :ivar id:
        The primary-key integer id of the record.
    :ivar uuid:
        The hexadecimal UUID of the record.
    :ivar source_type:
        The source style for the post generated.
    :ivar title:
        The title of the post.
    :ivar body:
        The body of the post.

    '''

    id = db.Column(db.Integer, primary_key=True)
    uuid = db.Column(db.String(32))
    source_type = db.Column(db.String)
    title = db.Column(db.String)
    body = db.Column(db.String)