"""Initial migration

Revision ID: 09862179bfb2
Revises: 
Create Date: 2020-07-05 09:35:37.577372

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09862179bfb2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('phc_record', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_phc_record_is_custom'), ['is_custom'], unique=False)

    with op.batch_alter_table('tifu_record', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tifu_record_is_custom'), ['is_custom'], unique=False)

    with op.batch_alter_table('wp_record', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_wp_record_is_custom'), ['is_custom'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wp_record', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_wp_record_is_custom'))

    with op.batch_alter_table('tifu_record', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tifu_record_is_custom'))

    with op.batch_alter_table('phc_record', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_phc_record_is_custom'))

    # ### end Alembic commands ###
