"""Added is_generated column to records

Revision ID: 45b8251ff686
Revises: 09862179bfb2
Create Date: 2020-07-13 12:52:54.810629

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45b8251ff686'
down_revision = '09862179bfb2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('phc_record', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_generated', sa.Boolean(), nullable=True))
        batch_op.create_index(batch_op.f('ix_phc_record_is_generated'), ['is_generated'], unique=False)

    with op.batch_alter_table('tifu_record', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_generated', sa.Boolean(), nullable=True))
        batch_op.create_index(batch_op.f('ix_tifu_record_is_generated'), ['is_generated'], unique=False)

    with op.batch_alter_table('wp_record', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_generated', sa.Boolean(), nullable=True))
        batch_op.create_index(batch_op.f('ix_wp_record_is_generated'), ['is_generated'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wp_record', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_wp_record_is_generated'))
        batch_op.drop_column('is_generated')

    with op.batch_alter_table('tifu_record', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tifu_record_is_generated'))
        batch_op.drop_column('is_generated')

    with op.batch_alter_table('phc_record', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_phc_record_is_generated'))
        batch_op.drop_column('is_generated')

    # ### end Alembic commands ###
