"""Tighter constraints on record metadata

Revision ID: 4c47105f58fa
Revises: 7b44a6113840
Create Date: 2020-07-20 17:11:05.884314

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c47105f58fa'
down_revision = '7b44a6113840'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('phc_record', schema=None) as batch_op:
        batch_op.alter_column('is_likes_prompted',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('prompted_author_username_end',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('prompted_comment_end',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('tifu_record', schema=None) as batch_op:
        batch_op.alter_column('post_body_prompt_end',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('post_title_prompt_end',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('wp_record', schema=None) as batch_op:
        batch_op.alter_column('prompted_prompt_end',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('prompted_response_end',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wp_record', schema=None) as batch_op:
        batch_op.alter_column('prompted_response_end',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('prompted_prompt_end',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('tifu_record', schema=None) as batch_op:
        batch_op.alter_column('post_title_prompt_end',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('post_body_prompt_end',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('phc_record', schema=None) as batch_op:
        batch_op.alter_column('prompted_comment_end',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('prompted_author_username_end',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('is_likes_prompted',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    # ### end Alembic commands ###
