import React, { Component, useState } from 'react';
import ConfigPanel from './ConfigPanel';
import Alert from 'react-bootstrap/Alert';
import Container from 'react-bootstrap/Container';
import Row from 'react-bootstrap/Row';
import Col from 'react-bootstrap/Col';
import Button from 'react-bootstrap/Button';
import './GamePage.css';

import axios from 'axios';
import { API_BASE_URL } from '../../App';

function DismissibleAlert(props) {
    const [show, setShow] = useState(true);

    if (show) {
        return (
            <Alert {...props} onClose={() => setShow(false)} dismissible>
                {props.children}
            </Alert>
        )
    }

    return null;
}

function Record(props) {
    let recordView = null;
    let postPanelClass = "post-panel";
    switch (props.type) {
        case 'tifu':
            recordView = (
                <h4 className="text-center mt-2 font-weight-bold">
                    {props.data.post_title}
                </h4>
            );
            break;
        case 'wp':
            recordView = (
                <h4 className="text-center mt-2 font-weight-bold">
                    {props.data.prompt}
                </h4>
            );
            break;
        case 'phc':
            recordView = (
                <div className="d-flex flex-column">
                    <span class="font-weight-bold phc-username">{props.data.author_username}</span>
                    <p class="comment-text mb-0">{props.data.comment}</p>
                </div>
            );
            postPanelClass += " phc-panel"
            break;
        default:
            return ( 'invalid record type!' )
    }

    return (
        <div className={`${postPanelClass} ${props.className}`}>
            {recordView}
        </div>  
    )
}

export default class GamePage extends Component {
    constructor(props) {
        super(props);
        this.state = {
            isConfigPanelVisible: true,
            hasError: false,
            hasGuessed: false,
            isGuessCorrect: false
        };
    }

    onConfigPanelReady = (configState) => {
        // Map the record types from a (string, bool) key/value pair to
        // an array of strings indicating the types to sample from.
        let recordTypes = [];
        for (const [key, value] of Object.entries(configState.recordTypes)) {
            if (!value) continue;
            recordTypes.push(key);
        }

        this.setState({
            gameConfig: {
                ...configState,
                recordTypes: recordTypes
            }
        }, () => {
            this.nextRecord();
        });
    }

    nextRecord = () => {
        // Randomly select record type
        const recordTypes = this.state.gameConfig.recordTypes;
        const recordType = recordTypes[Math.floor(Math.random() * recordTypes.length)];

        // Equal probability (50/50) of the record being generated by the AI or written by a human.
        const isRecordGenerated = Math.random() < 0.5;
        this.fetchRecord(recordType, isRecordGenerated);
    }

    fetchRecord = (recordType, isGenerated) => {
        const requestData = {
            // A "custom" record refers to a user-generated record
            'is_custom': false,
            // If a record is not generated, it means it was not 'written'
            // by the GPT2 model (i.e. it is written by a human).
            'is_generated': isGenerated,
        };

        this.setState({hasError: false, hasGuessed: false});
        axios.post(`${API_BASE_URL}/r/${recordType}/random`, {
            ...requestData,    
            headers: {
                'Content-Type': 'application/json'
            }
        })
        .then(response => {
            this.setState({
                currentRecord: {
                    data: response.data,
                    type: recordType
                }
            });
        })
        .catch(error => {
            this.setState({hasError: true});
            console.log(error);
        });
    }

    onGuessButtonClicked = (guessIsGenerated) => {
        const isCorrect = guessIsGenerated === this.state.currentRecord.data.is_generated;
        if (isCorrect) {
            console.log('WOWOWOWOWOOW AMAZING YOU GOT IT RIGHT');
        } else {
            console.log('you fucking suck');
        }

        this.setState({
            hasGuessed: true,
            isGuessCorrect: isCorrect
        });

        setTimeout(() => {
            this.nextRecord();
        }, 500);
    }

    render() {
        const showConfigPanel = this.state.currentRecord === undefined;
        return (
            <Container className="w-100 h-100 d-flex flex-column">
                <Row>
                    <Col sm="12" md="8" lg="6" className="mx-auto">
                        <div id="view-wrapper">
                            {
                                (this.state.hasError ? 
                                    (<DismissibleAlert variant="danger" className="error-alert">
                                        <Alert.Heading>server go brrr</Alert.Heading>
                                        This is probably an issue with our servers. Please try again later.
                                    </DismissibleAlert>)
                                : null)
                            }
                            {
                                (showConfigPanel ? 
                                    (<ConfigPanel action={this.onConfigPanelReady} />)
                                : (
                                    <div>
                                        <Record type={this.state.currentRecord.type}
                                            data={this.state.currentRecord.data}
                                            className={this.state.hasGuessed ? 
                                                (this.state.currentRecord.data.is_generated ? 
                                                    'post-ai' : 'post-human'
                                                ) : ''
                                            }
                                        />
                                        <div className="d-flex flex-row mt-4">
                                            <Button onClick={() => this.onGuessButtonClicked(true)} disabled={this.state.hasGuessed}
                                                size="lg" className={
                                                    `w-100 mr-3 select-btn select-ai-btn ${(
                                                        this.state.hasGuessed &&
                                                        !this.state.isGuessCorrect &&
                                                        this.state.currentRecord.data.is_generated ?
                                                        'highlight-border' : '')}`
                                                    }
                                            >
                                                robot
                                            </Button>
                                            <Button onClick={() => this.onGuessButtonClicked(false)} disabled={this.state.hasGuessed}
                                                size="lg" className={
                                                    `w-100 select-btn select-human-btn ${(
                                                        this.state.hasGuessed &&
                                                        !this.state.isGuessCorrect &&
                                                        !this.state.currentRecord.data.is_generated ?
                                                        'highlight-border' : '')}`
                                                    }
                                            >
                                                human
                                            </Button>
                                        </div>
                                    </div>
                                ))
                            }
                        </div>    
                    </Col>
                </Row>

                {
                    (showConfigPanel ? 
                        (<div className="mx-auto mt-auto py-4 text-center warn-footer">
                            <span className="font-weight-bold">warning:</span> posts are not reviewed and are probably <a 
                            href="https://www.pornsfw.com/" className="text-link">NSFW</a>, 
                            use at your own risk!
                        </div>)
                    : null)
                }    
            </Container>
        );
    }
}
